<?php
namespace Nebula\Meta;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class AlterTagReq
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'space_id',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'tag_name',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'tag_items',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Nebula\Meta\AlterSchemaItem',
                ),
        ),
        4 => array(
            'var' => 'schema_prop',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Nebula\Meta\SchemaProp',
        ),
    );

    /**
     * @var int
     */
    public $space_id = null;
    /**
     * @var string
     */
    public $tag_name = null;
    /**
     * @var \Nebula\Meta\AlterSchemaItem[]
     */
    public $tag_items = null;
    /**
     * @var \Nebula\Meta\SchemaProp
     */
    public $schema_prop = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['space_id'])) {
                $this->space_id = $vals['space_id'];
            }
            if (isset($vals['tag_name'])) {
                $this->tag_name = $vals['tag_name'];
            }
            if (isset($vals['tag_items'])) {
                $this->tag_items = $vals['tag_items'];
            }
            if (isset($vals['schema_prop'])) {
                $this->schema_prop = $vals['schema_prop'];
            }
        }
    }

    public function getName()
    {
        return 'AlterTagReq';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->space_id);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->tag_name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::LST) {
                        $this->tag_items = array();
                        $_size131 = 0;
                        $_etype134 = 0;
                        $xfer += $input->readListBegin($_etype134, $_size131);
                        for ($_i135 = 0; $_i135 < $_size131; ++$_i135) {
                            $elem136 = null;
                            $elem136 = new \Nebula\Meta\AlterSchemaItem();
                            $xfer += $elem136->read($input);
                            $this->tag_items []= $elem136;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRUCT) {
                        $this->schema_prop = new \Nebula\Meta\SchemaProp();
                        $xfer += $this->schema_prop->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('AlterTagReq');
        if ($this->space_id !== null) {
            $xfer += $output->writeFieldBegin('space_id', TType::I32, 1);
            $xfer += $output->writeI32($this->space_id);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tag_name !== null) {
            $xfer += $output->writeFieldBegin('tag_name', TType::STRING, 2);
            $xfer += $output->writeString($this->tag_name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tag_items !== null) {
            if (!is_array($this->tag_items)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('tag_items', TType::LST, 3);
            $output->writeListBegin(TType::STRUCT, count($this->tag_items));
            foreach ($this->tag_items as $iter137) {
                $xfer += $iter137->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->schema_prop !== null) {
            if (!is_object($this->schema_prop)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('schema_prop', TType::STRUCT, 4);
            $xfer += $this->schema_prop->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
