<?php
namespace Nebula\Meta;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Group
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'group_name',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'zone_names',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var string
     */
    public $group_name = null;
    /**
     * @var string[]
     */
    public $zone_names = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['group_name'])) {
                $this->group_name = $vals['group_name'];
            }
            if (isset($vals['zone_names'])) {
                $this->zone_names = $vals['zone_names'];
            }
        }
    }

    public function getName()
    {
        return 'Group';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->group_name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->zone_names = array();
                        $_size398 = 0;
                        $_etype401 = 0;
                        $xfer += $input->readListBegin($_etype401, $_size398);
                        for ($_i402 = 0; $_i402 < $_size398; ++$_i402) {
                            $elem403 = null;
                            $xfer += $input->readString($elem403);
                            $this->zone_names []= $elem403;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Group');
        if ($this->group_name !== null) {
            $xfer += $output->writeFieldBegin('group_name', TType::STRING, 1);
            $xfer += $output->writeString($this->group_name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->zone_names !== null) {
            if (!is_array($this->zone_names)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('zone_names', TType::LST, 2);
            $output->writeListBegin(TType::STRING, count($this->zone_names));
            foreach ($this->zone_names as $iter404) {
                $xfer += $output->writeString($iter404);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
