<?php
namespace Nebula\Meta;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class ListHostType
{
    const ALLOC = 0;

    const GRAPH = 1;

    const META = 2;

    const STORAGE = 3;

    static public $__names = array(
        0 => 'ALLOC',
        1 => 'GRAPH',
        2 => 'META',
        3 => 'STORAGE',
    );
}

