<?php
namespace Nebula\Meta;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface MetaServiceIf
{
    /**
     * @param \Nebula\Meta\CreateSpaceReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createSpace(\Nebula\Meta\CreateSpaceReq $req);
    /**
     * @param \Nebula\Meta\DropSpaceReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropSpace(\Nebula\Meta\DropSpaceReq $req);
    /**
     * @param \Nebula\Meta\GetSpaceReq $req
     * @return \Nebula\Meta\GetSpaceResp
     */
    public function getSpace(\Nebula\Meta\GetSpaceReq $req);
    /**
     * @param \Nebula\Meta\ListSpacesReq $req
     * @return \Nebula\Meta\ListSpacesResp
     */
    public function listSpaces(\Nebula\Meta\ListSpacesReq $req);
    /**
     * @param \Nebula\Meta\CreateSpaceAsReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createSpaceAs(\Nebula\Meta\CreateSpaceAsReq $req);
    /**
     * @param \Nebula\Meta\CreateTagReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createTag(\Nebula\Meta\CreateTagReq $req);
    /**
     * @param \Nebula\Meta\AlterTagReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function alterTag(\Nebula\Meta\AlterTagReq $req);
    /**
     * @param \Nebula\Meta\DropTagReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropTag(\Nebula\Meta\DropTagReq $req);
    /**
     * @param \Nebula\Meta\GetTagReq $req
     * @return \Nebula\Meta\GetTagResp
     */
    public function getTag(\Nebula\Meta\GetTagReq $req);
    /**
     * @param \Nebula\Meta\ListTagsReq $req
     * @return \Nebula\Meta\ListTagsResp
     */
    public function listTags(\Nebula\Meta\ListTagsReq $req);
    /**
     * @param \Nebula\Meta\CreateEdgeReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createEdge(\Nebula\Meta\CreateEdgeReq $req);
    /**
     * @param \Nebula\Meta\AlterEdgeReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function alterEdge(\Nebula\Meta\AlterEdgeReq $req);
    /**
     * @param \Nebula\Meta\DropEdgeReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropEdge(\Nebula\Meta\DropEdgeReq $req);
    /**
     * @param \Nebula\Meta\GetEdgeReq $req
     * @return \Nebula\Meta\GetEdgeResp
     */
    public function getEdge(\Nebula\Meta\GetEdgeReq $req);
    /**
     * @param \Nebula\Meta\ListEdgesReq $req
     * @return \Nebula\Meta\ListEdgesResp
     */
    public function listEdges(\Nebula\Meta\ListEdgesReq $req);
    /**
     * @param \Nebula\Meta\ListHostsReq $req
     * @return \Nebula\Meta\ListHostsResp
     */
    public function listHosts(\Nebula\Meta\ListHostsReq $req);
    /**
     * @param \Nebula\Meta\GetPartsAllocReq $req
     * @return \Nebula\Meta\GetPartsAllocResp
     */
    public function getPartsAlloc(\Nebula\Meta\GetPartsAllocReq $req);
    /**
     * @param \Nebula\Meta\ListPartsReq $req
     * @return \Nebula\Meta\ListPartsResp
     */
    public function listParts(\Nebula\Meta\ListPartsReq $req);
    /**
     * @param \Nebula\Meta\MultiPutReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function multiPut(\Nebula\Meta\MultiPutReq $req);
    /**
     * @param \Nebula\Meta\GetReq $req
     * @return \Nebula\Meta\GetResp
     */
    public function get(\Nebula\Meta\GetReq $req);
    /**
     * @param \Nebula\Meta\MultiGetReq $req
     * @return \Nebula\Meta\MultiGetResp
     */
    public function multiGet(\Nebula\Meta\MultiGetReq $req);
    /**
     * @param \Nebula\Meta\RemoveReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function remove(\Nebula\Meta\RemoveReq $req);
    /**
     * @param \Nebula\Meta\RemoveRangeReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function removeRange(\Nebula\Meta\RemoveRangeReq $req);
    /**
     * @param \Nebula\Meta\ScanReq $req
     * @return \Nebula\Meta\ScanResp
     */
    public function scan(\Nebula\Meta\ScanReq $req);
    /**
     * @param \Nebula\Meta\CreateTagIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createTagIndex(\Nebula\Meta\CreateTagIndexReq $req);
    /**
     * @param \Nebula\Meta\DropTagIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropTagIndex(\Nebula\Meta\DropTagIndexReq $req);
    /**
     * @param \Nebula\Meta\GetTagIndexReq $req
     * @return \Nebula\Meta\GetTagIndexResp
     */
    public function getTagIndex(\Nebula\Meta\GetTagIndexReq $req);
    /**
     * @param \Nebula\Meta\ListTagIndexesReq $req
     * @return \Nebula\Meta\ListTagIndexesResp
     */
    public function listTagIndexes(\Nebula\Meta\ListTagIndexesReq $req);
    /**
     * @param \Nebula\Meta\RebuildIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function rebuildTagIndex(\Nebula\Meta\RebuildIndexReq $req);
    /**
     * @param \Nebula\Meta\ListIndexStatusReq $req
     * @return \Nebula\Meta\ListIndexStatusResp
     */
    public function listTagIndexStatus(\Nebula\Meta\ListIndexStatusReq $req);
    /**
     * @param \Nebula\Meta\CreateEdgeIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createEdgeIndex(\Nebula\Meta\CreateEdgeIndexReq $req);
    /**
     * @param \Nebula\Meta\DropEdgeIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropEdgeIndex(\Nebula\Meta\DropEdgeIndexReq $req);
    /**
     * @param \Nebula\Meta\GetEdgeIndexReq $req
     * @return \Nebula\Meta\GetEdgeIndexResp
     */
    public function getEdgeIndex(\Nebula\Meta\GetEdgeIndexReq $req);
    /**
     * @param \Nebula\Meta\ListEdgeIndexesReq $req
     * @return \Nebula\Meta\ListEdgeIndexesResp
     */
    public function listEdgeIndexes(\Nebula\Meta\ListEdgeIndexesReq $req);
    /**
     * @param \Nebula\Meta\RebuildIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function rebuildEdgeIndex(\Nebula\Meta\RebuildIndexReq $req);
    /**
     * @param \Nebula\Meta\ListIndexStatusReq $req
     * @return \Nebula\Meta\ListIndexStatusResp
     */
    public function listEdgeIndexStatus(\Nebula\Meta\ListIndexStatusReq $req);
    /**
     * @param \Nebula\Meta\CreateUserReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createUser(\Nebula\Meta\CreateUserReq $req);
    /**
     * @param \Nebula\Meta\DropUserReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropUser(\Nebula\Meta\DropUserReq $req);
    /**
     * @param \Nebula\Meta\AlterUserReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function alterUser(\Nebula\Meta\AlterUserReq $req);
    /**
     * @param \Nebula\Meta\GrantRoleReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function grantRole(\Nebula\Meta\GrantRoleReq $req);
    /**
     * @param \Nebula\Meta\RevokeRoleReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function revokeRole(\Nebula\Meta\RevokeRoleReq $req);
    /**
     * @param \Nebula\Meta\ListUsersReq $req
     * @return \Nebula\Meta\ListUsersResp
     */
    public function listUsers(\Nebula\Meta\ListUsersReq $req);
    /**
     * @param \Nebula\Meta\ListRolesReq $req
     * @return \Nebula\Meta\ListRolesResp
     */
    public function listRoles(\Nebula\Meta\ListRolesReq $req);
    /**
     * @param \Nebula\Meta\GetUserRolesReq $req
     * @return \Nebula\Meta\ListRolesResp
     */
    public function getUserRoles(\Nebula\Meta\GetUserRolesReq $req);
    /**
     * @param \Nebula\Meta\ChangePasswordReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function changePassword(\Nebula\Meta\ChangePasswordReq $req);
    /**
     * @param \Nebula\Meta\HBReq $req
     * @return \Nebula\Meta\HBResp
     */
    public function heartBeat(\Nebula\Meta\HBReq $req);
    /**
     * @param \Nebula\Meta\BalanceReq $req
     * @return \Nebula\Meta\BalanceResp
     */
    public function balance(\Nebula\Meta\BalanceReq $req);
    /**
     * @param \Nebula\Meta\LeaderBalanceReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function leaderBalance(\Nebula\Meta\LeaderBalanceReq $req);
    /**
     * @param \Nebula\Meta\RegConfigReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function regConfig(\Nebula\Meta\RegConfigReq $req);
    /**
     * @param \Nebula\Meta\GetConfigReq $req
     * @return \Nebula\Meta\GetConfigResp
     */
    public function getConfig(\Nebula\Meta\GetConfigReq $req);
    /**
     * @param \Nebula\Meta\SetConfigReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function setConfig(\Nebula\Meta\SetConfigReq $req);
    /**
     * @param \Nebula\Meta\ListConfigsReq $req
     * @return \Nebula\Meta\ListConfigsResp
     */
    public function listConfigs(\Nebula\Meta\ListConfigsReq $req);
    /**
     * @param \Nebula\Meta\CreateSnapshotReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createSnapshot(\Nebula\Meta\CreateSnapshotReq $req);
    /**
     * @param \Nebula\Meta\DropSnapshotReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropSnapshot(\Nebula\Meta\DropSnapshotReq $req);
    /**
     * @param \Nebula\Meta\ListSnapshotsReq $req
     * @return \Nebula\Meta\ListSnapshotsResp
     */
    public function listSnapshots(\Nebula\Meta\ListSnapshotsReq $req);
    /**
     * @param \Nebula\Meta\AdminJobReq $req
     * @return \Nebula\Meta\AdminJobResp
     */
    public function runAdminJob(\Nebula\Meta\AdminJobReq $req);
    /**
     * @param \Nebula\Meta\AddZoneReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function addZone(\Nebula\Meta\AddZoneReq $req);
    /**
     * @param \Nebula\Meta\DropZoneReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropZone(\Nebula\Meta\DropZoneReq $req);
    /**
     * @param \Nebula\Meta\AddHostIntoZoneReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function addHostIntoZone(\Nebula\Meta\AddHostIntoZoneReq $req);
    /**
     * @param \Nebula\Meta\DropHostFromZoneReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropHostFromZone(\Nebula\Meta\DropHostFromZoneReq $req);
    /**
     * @param \Nebula\Meta\GetZoneReq $req
     * @return \Nebula\Meta\GetZoneResp
     */
    public function getZone(\Nebula\Meta\GetZoneReq $req);
    /**
     * @param \Nebula\Meta\ListZonesReq $req
     * @return \Nebula\Meta\ListZonesResp
     */
    public function listZones(\Nebula\Meta\ListZonesReq $req);
    /**
     * @param \Nebula\Meta\AddGroupReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function addGroup(\Nebula\Meta\AddGroupReq $req);
    /**
     * @param \Nebula\Meta\DropGroupReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropGroup(\Nebula\Meta\DropGroupReq $req);
    /**
     * @param \Nebula\Meta\AddZoneIntoGroupReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function addZoneIntoGroup(\Nebula\Meta\AddZoneIntoGroupReq $req);
    /**
     * @param \Nebula\Meta\DropZoneFromGroupReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropZoneFromGroup(\Nebula\Meta\DropZoneFromGroupReq $req);
    /**
     * @param \Nebula\Meta\GetGroupReq $req
     * @return \Nebula\Meta\GetGroupResp
     */
    public function getGroup(\Nebula\Meta\GetGroupReq $req);
    /**
     * @param \Nebula\Meta\ListGroupsReq $req
     * @return \Nebula\Meta\ListGroupsResp
     */
    public function listGroups(\Nebula\Meta\ListGroupsReq $req);
    /**
     * @param \Nebula\Meta\CreateBackupReq $req
     * @return \Nebula\Meta\CreateBackupResp
     */
    public function createBackup(\Nebula\Meta\CreateBackupReq $req);
    /**
     * @param \Nebula\Meta\RestoreMetaReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function restoreMeta(\Nebula\Meta\RestoreMetaReq $req);
    /**
     * @param \Nebula\Meta\AddListenerReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function addListener(\Nebula\Meta\AddListenerReq $req);
    /**
     * @param \Nebula\Meta\RemoveListenerReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function removeListener(\Nebula\Meta\RemoveListenerReq $req);
    /**
     * @param \Nebula\Meta\ListListenerReq $req
     * @return \Nebula\Meta\ListListenerResp
     */
    public function listListener(\Nebula\Meta\ListListenerReq $req);
    /**
     * @param \Nebula\Meta\GetStatsReq $req
     * @return \Nebula\Meta\GetStatsResp
     */
    public function getStats(\Nebula\Meta\GetStatsReq $req);
    /**
     * @param \Nebula\Meta\SignInFTServiceReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function signInFTService(\Nebula\Meta\SignInFTServiceReq $req);
    /**
     * @param \Nebula\Meta\SignOutFTServiceReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function signOutFTService(\Nebula\Meta\SignOutFTServiceReq $req);
    /**
     * @param \Nebula\Meta\ListFTClientsReq $req
     * @return \Nebula\Meta\ListFTClientsResp
     */
    public function listFTClients(\Nebula\Meta\ListFTClientsReq $req);
    /**
     * @param \Nebula\Meta\CreateFTIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function createFTIndex(\Nebula\Meta\CreateFTIndexReq $req);
    /**
     * @param \Nebula\Meta\DropFTIndexReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function dropFTIndex(\Nebula\Meta\DropFTIndexReq $req);
    /**
     * @param \Nebula\Meta\ListFTIndexesReq $req
     * @return \Nebula\Meta\ListFTIndexesResp
     */
    public function listFTIndexes(\Nebula\Meta\ListFTIndexesReq $req);
    /**
     * @param \Nebula\Meta\CreateSessionReq $req
     * @return \Nebula\Meta\CreateSessionResp
     */
    public function createSession(\Nebula\Meta\CreateSessionReq $req);
    /**
     * @param \Nebula\Meta\UpdateSessionsReq $req
     * @return \Nebula\Meta\UpdateSessionsResp
     */
    public function updateSessions(\Nebula\Meta\UpdateSessionsReq $req);
    /**
     * @param \Nebula\Meta\ListSessionsReq $req
     * @return \Nebula\Meta\ListSessionsResp
     */
    public function listSessions(\Nebula\Meta\ListSessionsReq $req);
    /**
     * @param \Nebula\Meta\GetSessionReq $req
     * @return \Nebula\Meta\GetSessionResp
     */
    public function getSession(\Nebula\Meta\GetSessionReq $req);
    /**
     * @param \Nebula\Meta\RemoveSessionReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function removeSession(\Nebula\Meta\RemoveSessionReq $req);
    /**
     * @param \Nebula\Meta\KillQueryReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function killQuery(\Nebula\Meta\KillQueryReq $req);
    /**
     * @param \Nebula\Meta\ReportTaskReq $req
     * @return \Nebula\Meta\ExecResp
     */
    public function reportTaskFinish(\Nebula\Meta\ReportTaskReq $req);
    /**
     * @param \Nebula\Meta\ListClusterInfoReq $req
     * @return \Nebula\Meta\ListClusterInfoResp
     */
    public function listCluster(\Nebula\Meta\ListClusterInfoReq $req);
    /**
     * @param \Nebula\Meta\GetMetaDirInfoReq $req
     * @return \Nebula\Meta\GetMetaDirInfoResp
     */
    public function getMetaDirInfo(\Nebula\Meta\GetMetaDirInfoReq $req);
    /**
     * @param \Nebula\Meta\VerifyClientVersionReq $req
     * @return \Nebula\Meta\VerifyClientVersionResp
     */
    public function verifyClientVersion(\Nebula\Meta\VerifyClientVersionReq $req);
}
