<?php
namespace Nebula\Meta;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class TaskResult
{
    const SUCCEEDED = 0;

    const FAILED = 1;

    const IN_PROGRESS = 2;

    const INVALID = 3;

    static public $__names = array(
        0 => 'SUCCEEDED',
        1 => 'FAILED',
        2 => 'IN_PROGRESS',
        3 => 'INVALID',
    );
}

