<?php
namespace Nebula\Meta;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class UpdateSessionsResp
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'code',
            'isRequired' => false,
            'type' => TType::I32,
            'class' => '\Nebula\Common\ErrorCode',
        ),
        2 => array(
            'var' => 'leader',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Nebula\Common\HostAddr',
        ),
        3 => array(
            'var' => 'killed_queries',
            'isRequired' => false,
            'type' => TType::MAP,
            'ktype' => TType::I64,
            'vtype' => TType::MAP,
            'key' => array(
                'type' => TType::I64,
            ),
            'val' => array(
                'type' => TType::MAP,
                'ktype' => TType::I64,
                'vtype' => TType::STRUCT,
                'key' => array(
                    'type' => TType::I64,
                ),
                'val' => array(
                    'type' => TType::STRUCT,
                    'class' => '\Nebula\Meta\QueryDesc',
                    ),
                ),
        ),
    );

    /**
     * @var int
     */
    public $code = null;
    /**
     * @var \Nebula\Common\HostAddr
     */
    public $leader = null;
    /**
     * @var array
     */
    public $killed_queries = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['code'])) {
                $this->code = $vals['code'];
            }
            if (isset($vals['leader'])) {
                $this->leader = $vals['leader'];
            }
            if (isset($vals['killed_queries'])) {
                $this->killed_queries = $vals['killed_queries'];
            }
        }
    }

    public function getName()
    {
        return 'UpdateSessionsResp';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->code);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->leader = new \Nebula\Common\HostAddr();
                        $xfer += $this->leader->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::MAP) {
                        $this->killed_queries = array();
                        $_size532 = 0;
                        $_ktype533 = 0;
                        $_vtype534 = 0;
                        $xfer += $input->readMapBegin($_ktype533, $_vtype534, $_size532);
                        for ($_i536 = 0; $_i536 < $_size532; ++$_i536) {
                            $key537 = 0;
                            $val538 = array();
                            $xfer += $input->readI64($key537);
                            $val538 = array();
                            $_size539 = 0;
                            $_ktype540 = 0;
                            $_vtype541 = 0;
                            $xfer += $input->readMapBegin($_ktype540, $_vtype541, $_size539);
                            for ($_i543 = 0; $_i543 < $_size539; ++$_i543) {
                                $key544 = 0;
                                $val545 = new \Nebula\Meta\QueryDesc();
                                $xfer += $input->readI64($key544);
                                $val545 = new \Nebula\Meta\QueryDesc();
                                $xfer += $val545->read($input);
                                $val538[$key544] = $val545;
                            }
                            $xfer += $input->readMapEnd();
                            $this->killed_queries[$key537] = $val538;
                        }
                        $xfer += $input->readMapEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('UpdateSessionsResp');
        if ($this->code !== null) {
            $xfer += $output->writeFieldBegin('code', TType::I32, 1);
            $xfer += $output->writeI32($this->code);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->leader !== null) {
            if (!is_object($this->leader)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('leader', TType::STRUCT, 2);
            $xfer += $this->leader->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->killed_queries !== null) {
            if (!is_array($this->killed_queries)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('killed_queries', TType::MAP, 3);
            $output->writeMapBegin(TType::I64, TType::MAP, count($this->killed_queries));
            foreach ($this->killed_queries as $kiter546 => $viter547) {
                $xfer += $output->writeI64($kiter546);
                $output->writeMapBegin(TType::I64, TType::STRUCT, count($viter547));
                foreach ($viter547 as $kiter548 => $viter549) {
                    $xfer += $output->writeI64($kiter548);
                    $xfer += $viter549->write($output);
                }
                $output->writeMapEnd();
            }
            $output->writeMapEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
