<?php
namespace Nebula\Storage;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class LookupIndexRequest
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'space_id',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'parts',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::I32,
            'elem' => array(
                'type' => TType::I32,
                ),
        ),
        3 => array(
            'var' => 'indices',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Nebula\Storage\IndexSpec',
        ),
        4 => array(
            'var' => 'return_columns',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        5 => array(
            'var' => 'common',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Nebula\Storage\RequestCommon',
        ),
        6 => array(
            'var' => 'limit',
            'isRequired' => false,
            'type' => TType::I64,
        ),
    );

    /**
     * @var int
     */
    public $space_id = null;
    /**
     * @var int[]
     */
    public $parts = null;
    /**
     * @var \Nebula\Storage\IndexSpec
     */
    public $indices = null;
    /**
     * @var string[]
     */
    public $return_columns = null;
    /**
     * @var \Nebula\Storage\RequestCommon
     */
    public $common = null;
    /**
     * @var int
     */
    public $limit = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['space_id'])) {
                $this->space_id = $vals['space_id'];
            }
            if (isset($vals['parts'])) {
                $this->parts = $vals['parts'];
            }
            if (isset($vals['indices'])) {
                $this->indices = $vals['indices'];
            }
            if (isset($vals['return_columns'])) {
                $this->return_columns = $vals['return_columns'];
            }
            if (isset($vals['common'])) {
                $this->common = $vals['common'];
            }
            if (isset($vals['limit'])) {
                $this->limit = $vals['limit'];
            }
        }
    }

    public function getName()
    {
        return 'LookupIndexRequest';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->space_id);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->parts = array();
                        $_size312 = 0;
                        $_etype315 = 0;
                        $xfer += $input->readListBegin($_etype315, $_size312);
                        for ($_i316 = 0; $_i316 < $_size312; ++$_i316) {
                            $elem317 = null;
                            $xfer += $input->readI32($elem317);
                            $this->parts []= $elem317;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->indices = new \Nebula\Storage\IndexSpec();
                        $xfer += $this->indices->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::LST) {
                        $this->return_columns = array();
                        $_size318 = 0;
                        $_etype321 = 0;
                        $xfer += $input->readListBegin($_etype321, $_size318);
                        for ($_i322 = 0; $_i322 < $_size318; ++$_i322) {
                            $elem323 = null;
                            $xfer += $input->readString($elem323);
                            $this->return_columns []= $elem323;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRUCT) {
                        $this->common = new \Nebula\Storage\RequestCommon();
                        $xfer += $this->common->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->limit);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('LookupIndexRequest');
        if ($this->space_id !== null) {
            $xfer += $output->writeFieldBegin('space_id', TType::I32, 1);
            $xfer += $output->writeI32($this->space_id);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->parts !== null) {
            if (!is_array($this->parts)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('parts', TType::LST, 2);
            $output->writeListBegin(TType::I32, count($this->parts));
            foreach ($this->parts as $iter324) {
                $xfer += $output->writeI32($iter324);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->indices !== null) {
            if (!is_object($this->indices)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('indices', TType::STRUCT, 3);
            $xfer += $this->indices->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->return_columns !== null) {
            if (!is_array($this->return_columns)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('return_columns', TType::LST, 4);
            $output->writeListBegin(TType::STRING, count($this->return_columns));
            foreach ($this->return_columns as $iter325) {
                $xfer += $output->writeString($iter325);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->common !== null) {
            if (!is_object($this->common)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('common', TType::STRUCT, 5);
            $xfer += $this->common->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->limit !== null) {
            $xfer += $output->writeFieldBegin('limit', TType::I64, 6);
            $xfer += $output->writeI64($this->limit);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
