<?php
namespace Nebula\Common;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Date
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'year',
            'isRequired' => false,
            'type' => TType::I16,
        ),
        2 => array(
            'var' => 'month',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
        3 => array(
            'var' => 'day',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
    );

    /**
     * @var int
     */
    public $year = null;
    /**
     * @var int
     */
    public $month = null;
    /**
     * @var int
     */
    public $day = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['year'])) {
                $this->year = $vals['year'];
            }
            if (isset($vals['month'])) {
                $this->month = $vals['month'];
            }
            if (isset($vals['day'])) {
                $this->day = $vals['day'];
            }
        }
    }

    public function getName()
    {
        return 'Date';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->year);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->month);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->day);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Date');
        if ($this->year !== null) {
            $xfer += $output->writeFieldBegin('year', TType::I16, 1);
            $xfer += $output->writeI16($this->year);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->month !== null) {
            $xfer += $output->writeFieldBegin('month', TType::BYTE, 2);
            $xfer += $output->writeByte($this->month);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->day !== null) {
            $xfer += $output->writeFieldBegin('day', TType::BYTE, 3);
            $xfer += $output->writeByte($this->day);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
