<?php
namespace Nebula\Common;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Time
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'hour',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
        2 => array(
            'var' => 'minute',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
        3 => array(
            'var' => 'sec',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
        4 => array(
            'var' => 'microsec',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $hour = null;
    /**
     * @var int
     */
    public $minute = null;
    /**
     * @var int
     */
    public $sec = null;
    /**
     * @var int
     */
    public $microsec = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['hour'])) {
                $this->hour = $vals['hour'];
            }
            if (isset($vals['minute'])) {
                $this->minute = $vals['minute'];
            }
            if (isset($vals['sec'])) {
                $this->sec = $vals['sec'];
            }
            if (isset($vals['microsec'])) {
                $this->microsec = $vals['microsec'];
            }
        }
    }

    public function getName()
    {
        return 'Time';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->hour);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->minute);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->sec);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->microsec);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Time');
        if ($this->hour !== null) {
            $xfer += $output->writeFieldBegin('hour', TType::BYTE, 1);
            $xfer += $output->writeByte($this->hour);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->minute !== null) {
            $xfer += $output->writeFieldBegin('minute', TType::BYTE, 2);
            $xfer += $output->writeByte($this->minute);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sec !== null) {
            $xfer += $output->writeFieldBegin('sec', TType::BYTE, 3);
            $xfer += $output->writeByte($this->sec);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->microsec !== null) {
            $xfer += $output->writeFieldBegin('microsec', TType::I32, 4);
            $xfer += $output->writeI32($this->microsec);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
