<?php
namespace Nebula\Common;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Vertex
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'vid',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Nebula\Common\Value',
        ),
        2 => array(
            'var' => 'tags',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Nebula\Common\Tag',
                ),
        ),
    );

    /**
     * @var \Nebula\Common\Value
     */
    public $vid = null;
    /**
     * @var \Nebula\Common\Tag[]
     */
    public $tags = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['vid'])) {
                $this->vid = $vals['vid'];
            }
            if (isset($vals['tags'])) {
                $this->tags = $vals['tags'];
            }
        }
    }

    public function getName()
    {
        return 'Vertex';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->vid = new \Nebula\Common\Value();
                        $xfer += $this->vid->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->tags = array();
                        $_size75 = 0;
                        $_etype78 = 0;
                        $xfer += $input->readListBegin($_etype78, $_size75);
                        for ($_i79 = 0; $_i79 < $_size75; ++$_i79) {
                            $elem80 = null;
                            $elem80 = new \Nebula\Common\Tag();
                            $xfer += $elem80->read($input);
                            $this->tags []= $elem80;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Vertex');
        if ($this->vid !== null) {
            if (!is_object($this->vid)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('vid', TType::STRUCT, 1);
            $xfer += $this->vid->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tags !== null) {
            if (!is_array($this->tags)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('tags', TType::LST, 2);
            $output->writeListBegin(TType::STRUCT, count($this->tags));
            foreach ($this->tags as $iter81) {
                $xfer += $iter81->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
